// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPF.RecuperacionTecnologica.Web.Data;

#nullable disable

namespace TPF.RecuperacionTecnologica.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003123114_InicialDominio")]
    partial class InicialDominio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Asignacion", b =>
                {
                    b.Property<int>("NroAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroAsignacion"));

                    b.Property<int>("CodigoCoordinador")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAsignacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaLiberacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("JustificacionCambio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoLiberacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NroEquipo")
                        .HasColumnType("int");

                    b.Property<int>("NroSolicitud")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("NroAsignacion");

                    b.HasIndex("CodigoCoordinador");

                    b.HasIndex("NroEquipo");

                    b.HasIndex("NroSolicitud");

                    b.ToTable("Asignaciones", t =>
                        {
                            t.HasCheckConstraint("CK_Asignacion_FechaLiberacion_Coherente", "[FechaLiberacion] IS NULL OR [FechaLiberacion] >= [FechaAsignacion]");
                        });
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.ConfiguracionInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CodigoAdministrador")
                        .HasColumnType("int");

                    b.Property<int>("DiasLimiteRetiro")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreOrganizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ZonaCobertura")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAdministrador");

                    b.ToTable("ConfiguracionInstitucional", t =>
                        {
                            t.HasCheckConstraint("CK_ConfiguracionInstitucional_Id_Unico", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Diagnostico", b =>
                {
                    b.Property<int>("NroDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroDiagnostico"));

                    b.Property<int>("CodigoTecnico")
                        .HasColumnType("int");

                    b.Property<string>("DetalleFallas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DetalleReparacionesRealizadas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DiagnosticoRectificadoId")
                        .HasColumnType("int");

                    b.Property<int>("DictamenTecnico")
                        .HasColumnType("int");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("NroEquipo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoDiagnostico")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EspecificacionesVerificadas", "TPF.RecuperacionTecnologica.Web.Models.Diagnostico.EspecificacionesVerificadas#EspecificacionesTecnicas", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Almacenamiento")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("EstadoBateria")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("MemoriaRam")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Otros")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("Procesador")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("TamanoPantalla")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.HasKey("NroDiagnostico");

                    b.HasIndex("CodigoTecnico");

                    b.HasIndex("DiagnosticoRectificadoId");

                    b.HasIndex("NroEquipo");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Entrega", b =>
                {
                    b.Property<int>("NroEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroEntrega"));

                    b.Property<int>("CodigoCoordinador")
                        .HasColumnType("int");

                    b.Property<string>("DocumentoIdentidadQuienRetira")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("NroAsignacion")
                        .HasColumnType("int");

                    b.Property<int>("NroEquipo")
                        .HasColumnType("int");

                    b.Property<int>("NroSolicitud")
                        .HasColumnType("int");

                    b.HasKey("NroEntrega");

                    b.HasIndex("CodigoCoordinador");

                    b.HasIndex("NroAsignacion");

                    b.HasIndex("NroEquipo");

                    b.HasIndex("NroSolicitud");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Equipo", b =>
                {
                    b.Property<int>("NroEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroEquipo"));

                    b.Property<int>("EstadoEquipo")
                        .HasColumnType("int");

                    b.Property<int>("EstadoInicialDeclarado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDisponibilidad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NroUsuarioDonante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TipoEquipo")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EspecificacionesDeclaradas", "TPF.RecuperacionTecnologica.Web.Models.Equipo.EspecificacionesDeclaradas#EspecificacionesTecnicas", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Almacenamiento")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("EstadoBateria")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("MemoriaRam")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");

                            b1.Property<string>("Otros")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("Procesador")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("TamanoPantalla")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)");
                        });

                    b.HasKey("NroEquipo");

                    b.HasIndex("NroUsuarioDonante");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.ImagenEquipo", b =>
                {
                    b.Property<int>("NroImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroImagen"));

                    b.Property<string>("Angulo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("FechaCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("NroDiagnostico")
                        .HasColumnType("int");

                    b.Property<int>("NroEquipo")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("NroImagen");

                    b.HasIndex("NroDiagnostico");

                    b.HasIndex("NroEquipo");

                    b.ToTable("ImagenesEquipo");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Personal", b =>
                {
                    b.Property<int>("CodigoPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoPersonal"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("EstadoPersonal")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaInactivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotivoInactivacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolAsignado")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CodigoPersonal");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.ToTable("PersonalInterno", t =>
                        {
                            t.HasCheckConstraint("CK_Personal_Dni_SoloDigitos", "[Dni] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.RegistroAuditoria", b =>
                {
                    b.Property<int>("NroAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroAuditoria"));

                    b.Property<int?>("CodigoPersonal")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdEntidadAfectada")
                        .HasColumnType("int");

                    b.Property<int>("TipoOperacion")
                        .HasColumnType("int");

                    b.HasKey("NroAuditoria");

                    b.HasIndex("CodigoPersonal");

                    b.ToTable("RegistrosAuditoria");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Solicitud", b =>
                {
                    b.Property<int>("NroSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroSolicitud"));

                    b.Property<int?>("CodigoCoordinador")
                        .HasColumnType("int");

                    b.Property<int>("EstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MotivoSolicitud")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NroEquipoRequerido")
                        .HasColumnType("int");

                    b.Property<int>("NroUsuario")
                        .HasColumnType("int");

                    b.Property<int>("OrigenSolicitud")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TipoSolicitante")
                        .HasColumnType("int");

                    b.HasKey("NroSolicitud");

                    b.HasIndex("CodigoCoordinador");

                    b.HasIndex("NroEquipoRequerido");

                    b.HasIndex("NroUsuario");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Usuario", b =>
                {
                    b.Property<int>("NroUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroUsuario"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotivoBaja")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("NroUsuario");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("NroDocumento")
                        .IsUnique();

                    b.ToTable("Usuarios", t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_FechaBaja_Coherente", "[FechaBaja] IS NULL OR [FechaBaja] >= [FechaAlta]");

                            t.HasCheckConstraint("CK_Usuario_NroDocumento_SoloDigitos", "[NroDocumento] NOT LIKE '%[^0-9]%'");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Asignacion", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Personal", "Coordinador")
                        .WithMany()
                        .HasForeignKey("CodigoCoordinador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("NroEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("NroSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinador");

                    b.Navigation("Equipo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.ConfiguracionInstitucional", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Personal", "Administrador")
                        .WithMany()
                        .HasForeignKey("CodigoAdministrador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Diagnostico", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Personal", "Tecnico")
                        .WithMany()
                        .HasForeignKey("CodigoTecnico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Diagnostico", "DiagnosticoRectificado")
                        .WithMany()
                        .HasForeignKey("DiagnosticoRectificadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("NroEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiagnosticoRectificado");

                    b.Navigation("Equipo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Entrega", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Personal", "Coordinador")
                        .WithMany()
                        .HasForeignKey("CodigoCoordinador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Asignacion", "Asignacion")
                        .WithMany()
                        .HasForeignKey("NroAsignacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("NroEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("NroSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Coordinador");

                    b.Navigation("Equipo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Equipo", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Usuario", "UsuarioDonante")
                        .WithMany()
                        .HasForeignKey("NroUsuarioDonante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioDonante");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.ImagenEquipo", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Diagnostico", "Diagnostico")
                        .WithMany()
                        .HasForeignKey("NroDiagnostico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("NroEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagnostico");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.RegistroAuditoria", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("CodigoPersonal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("TPF.RecuperacionTecnologica.Web.Models.Solicitud", b =>
                {
                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Personal", "Coordinador")
                        .WithMany()
                        .HasForeignKey("CodigoCoordinador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Equipo", "EquipoRequerido")
                        .WithMany()
                        .HasForeignKey("NroEquipoRequerido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPF.RecuperacionTecnologica.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("NroUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinador");

                    b.Navigation("EquipoRequerido");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
